services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .docker.env
    depends_on:
      - db
      - rabbitmq
    volumes:
      - .:/app

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .docker.env
    ports:
      - "${POSTGRES_PORT_OUT:-5432}:5432"

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"  
      - "15672:15672"  
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    

  celery_worker:
    build: .
    command: celery -A app.celery.celery_app worker -l info
    env_file:
      - .docker.env
    depends_on:
      - db
      - rabbitmq
    volumes:
      - .:/app

volumes:
  postgres_data:
  rabbitmq_data:
