FROM python:3.12-slim

WORKDIR /app

# Install system dependencies and setup poetry
RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential libpq-dev && \
    rm -rf /var/lib/apt/lists/* && \
    pip install poetry

# Copy poetry files
COPY pyproject.toml poetry.lock ./

# Install dependencies
RUN poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi --with dev

# Copy application code
COPY . .

# Set environment variables
ENV PYTHONPATH=/app

CMD ["poetry", "run", "pytest", "./tests", "--cache-clear"]