services:
  test_db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .docker.env
    environment:
      - POSTGRES_USER=${TEST_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}
      - POSTGRES_DB=${TEST_POSTGRES_DB}
    ports:
      - "${TEST_POSTGRES_PORT_OUT:-5432}:5432"

  test_runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - .docker.env
    depends_on:
      - test_db
    volumes:
      - .:/app

volumes:
  postgres_data:
