services:
  test_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${TEST_POSTGRES_DB:-postgres}
    env_file:
      - .docker.env
    ports:
      - "5433:5432"

  test_runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - .docker.env
    depends_on:
      - test_db
    volumes:
      - .:/app

