"""add task_id

Revision ID: c7b7fe981cdc
Revises: 3f5276f51309
Create Date: 2024-11-10 17:08:39.653566

"""
from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c7b7fe981cdc'
down_revision: str | None = '3f5276f51309'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecg', sa.Column('task_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ecg', 'task_id')
    # ### end Alembic commands ###
